version: '3.8'

services:
  hardline_backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: hardline_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - hardline_postgres
    command: npm run dev
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512m"



  hardline_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5452:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

